# URL de conexi�n a PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7ie6qcvikkc73egkvrg-a.frankfurt-postgres.render.com:5432/postgres_loantech

# Usuario y contrase�a de PostgreSQL
spring.datasource.username=postgres_loantech_user
spring.datasource.password=6O50C3auDcBe7RhekLuZx03OV9JE799w
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always