services:
  postgres-db:
    container_name: prestamos-db-postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - prestamos-network
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  postgres_data:

networks:
  prestamos-network:
    driver: bridge