services:
  postgres-db:
    container_name: prestamos-db-postgres-dev
    image: postgres:12-alpine
    restart: "no"
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - prestamos-network
    ports:
      - ${POSTGRES_PORT}:5432

  backend:
    container_name: prestamos-backend-dev
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - prestamos-network
    depends_on:
      - postgres-db
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: prestamos-frontend-dev
    build:
      context: ./frontend
    ports:
      - "5175:5175"
    networks:
      - prestamos-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  prestamos-network:
    driver: bridge